### ISSUE TITLE
Link to blog

### ISSUE THREAD

**Issue by justinyangusa** [HackIllinois/site-2019#15]
Something we have been talking about is creating more visibility for the blog. Part of this push would involve adding a link to the blog at the bottom of the 404 page with the other links. I can put up a PR if this idea sounds ok.

**Comment by ASankaran** [comment]
That idea sounds good to me. 

Any thoughts from @smg155 @apa-123 since this is a content related question?

**Comment by apa-123** [comment]
I like it too!
